### PR TITLE
Fix buggy list comprehension.

### PR DESCRIPTION
**Pull request by esirK**
## Description
Fixes # (issue)
Fixes bug where list dict comprehension that was being used was replacing contents rather than updating them.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by esirK** [comment]
@kilemensi  I manually tested all the other sheets and these are the only ones remaining with the described bug.

**Comment by kilemensi** [comment]
> @kilemensi I manually tested all the other sheets and these are the only ones remaining with the described bug.

Since we did a lot of copy and paste, I’m sure even new sheets will have this bug e.g. [this one](https://github.com/CodeForAfrica/gmmp/blob/a71a9b7c4d523348ce08016d5f7b25e2c36d477c/reports/report_builder.py#L3341)

**Comment by esirK** [comment]
@kilemensi  the bug only affected sheets requiring **MAJOR_TOPIC** to be extracted from **TOPIC_GROUPS**. This has been fixed.

**Comment by kilemensi** [comment]
> @kilemensi the bug only affected sheets requiring **MAJOR_TOPIC** to be extracted from **TOPIC_GROUPS**. This has been fixed.

I'm a bit uneasy about this @esirK : Are you sure it won't affect queries like [ws_08](https://github.com/CodeForAfrica/gmmp/blob/9cc32142aa397edaf04e1c49087b0dc4c1ee6518/reports/report_builder.py#L728)? I'd rather we "fix" all of them just in case.

**Comment by esirK** [comment]
> > @kilemensi the bug only affected sheets requiring **MAJOR_TOPIC** to be extracted from **TOPIC_GROUPS**. This has been fixed.
> 
> I'm a bit uneasy about this @esirK : Are you sure it won't affect queries like [ws_08](https://github.com/CodeForAfrica/gmmp/blob/9cc32142aa397edaf04e1c49087b0dc4c1ee6518/reports/report_builder.py#L728)? I'd rather we "fix" all of them just in case.

No, it shouldn't affect anything else. The reason being [TOPIC_GROUPS](https://github.com/CodeForAfrica/gmmp/blob/9cc32142aa/reports/report_details.py#L2203) is the only group that has keys that can get overwritten for all the others, the keys are unique and thus the approach used isn't a bug. 
For example `ws_08` would only be affected if [SCOPE](https://github.com/CodeForAfrica/gmmp/blob/9cc32142aa/forms/modelutils.py#L100) had duplicate tuples(Which we don't want to allow.)

**Comment by kilemensi** [comment]
> > > @kilemensi the bug only affected sheets requiring **MAJOR_TOPIC** to be extracted from **TOPIC_GROUPS**. This has been fixed.
> > 
> > 
> > I'm a bit uneasy about this @esirK : Are you sure it won't affect queries like [ws_08](https://github.com/CodeForAfrica/gmmp/blob/9cc32142aa397edaf04e1c49087b0dc4c1ee6518/reports/report_builder.py#L728)? I'd rather we "fix" all of them just in case.
> 
> No, it shouldn't affect anything else. The reason being [TOPIC_GROUPS](https://github.com/CodeForAfrica/gmmp/blob/9cc32142aa/reports/report_details.py#L2203) is the only group that has keys that can get overwritten for all the others, the keys are unique and thus the approach used isn't a bug.
> For example `ws_08` would only be affected if [SCOPE](https://github.com/CodeForAfrica/gmmp/blob/9cc32142aa/forms/modelutils.py#L100) had duplicate tuples(Which we don't want to allow.)

Alright, alright... with heavy heart, I'll go and approve it knowing in the near future some poor soul will suffer the same fate we've just suffered when they introduce a mapping that can have duplicate values 😢

**Review by kilemensi — APPROVED** [review]
🚀

**Pull request merged**
