### PR TITLE
[Chore] Upgrade dependencies

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

Upgrade dependencies since some are now a security risk.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

Screenshot from 2021-04-22 08-38-11

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by esirK** [comment]
@kilemensi 
The updates aren't affecting anything as far as my manual testing goes. 
The packages `django-grappelli==2.14.4` and `django-debug-toolbar== 3.2.1` aren't being used anywhere as far as I can tell. Should we remove them?

**Comment by kilemensi** [comment]
> @kilemensi
> The updates aren't affecting anything as far as my manual testing goes.
> The packages `django-grappelli==2.14.4` and `django-debug-toolbar== 3.2.1` aren't being used anywhere as far as I can tell. Should we remove them?

If we're sure @esirK ... lets dependencies is always better but I saw: https://github.com/CodeForAfrica/gmmp/blob/f16ae1cc432bf535d1bbb6e9fc68f4075df46319/gmmp/settings.py#L96-L102

**Comment by esirK** [comment]
@kilemensi Yes we have that but it doesn't seem to work (I can't see the toolbar) I'll do some debugging to see why it doesn't work.

**Comment by esirK** [comment]
@kilemensi  I've updated it.

Screenshot 2021-04-22 at 12 13 27

**Comment by kilemensi** [comment]
> @kilemensi I've updated it.
> 
Can all toolbar settings be setup only when DEBUG is `True` @esirK ? We don't want it in production (Unless it internally checks for DEBUG).

**Comment by esirK** [comment]
@kilemensi  I think we're good now.

**Comment by kilemensi** [comment]
> @kilemensi I think we're good now.

Can't the middleware also be added only `if  DEBUG:`? Otherwise, lets merge this @esirK .

**Comment by esirK** [comment]
> Can't the middleware also be added only `if DEBUG:`? Otherwise, lets merge this @esirK .

It is possible @kilemensi 
I actually tried it but the problem was as specified in their [docs](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#enabling-middleware), it should come as early as possible otherwise it won't work. 
The other approach we could have is something like 
```
MIDDLEWARE = []
if DEBUG:
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]

MIDDLEWARE +=[
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "gmmp.middlewares.ProtectedStaticFileMiddleware",
]
```
which is okay too. I think.

**Review by esirK — APPROVED** [review]

**Pull request merged**
