### PR TITLE
Updated queries for sheet 50-60

### PR DESCRIPTION
**Pull request by esirK**
## Description

Includes updated queries for sheet 50-60

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
# 50 
Screenshot 2021-03-08 at 14 54 14

# 51
Screenshot 2021-03-08 at 14 55 16

# 52
Screenshot 2021-03-08 at 14 56 48

# 55
Screenshot 2021-03-08 at 15 01 52

# 56
Screenshot 2021-03-08 at 15 02 01

# 57
Screenshot 2021-03-08 at 15 02 12

# 58
Screenshot 2021-03-08 at 15 02 20

# 59
Screenshot 2021-03-08 at 15 02 26

# 60
Screenshot 2021-03-08 at 15 02 54

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
👍🏾 @esirK 


-------------------------

1. [55 & 56](https://docs.google.com/spreadsheets/d/1FV6pUcW3hEade4y17ENGAP5Dp4RkNnDW/edit#gid=1308543941&range=13:14):

    * Should include **Twitter** i.e. not just `Internet`,
    * `.filter(country__in=self.country_list)` is missing (may be this is where `country_field` is meant to be used?).

2. 57 - 60

    * `.filter(country__in=self.country_list)` is missing (may be this is where `country_field` is meant to be used?).

**Comment by esirK** [comment]
👍 @kilemensi  
just to confirm, how will sheets 55 & 56 look like in the report? Like the current sheet 57?

**Comment by esirK** [comment]
for 
>.filter(country__in=self.country_list) is missing (may be this is where country_field is meant to be used?).

this filter isn't applicable here because `person_models` don't have a country. The `country_field` is used inside the `apply_weights` function.

**Comment by kilemensi** [comment]
> 
> this filter isn't applicable here because `person_models` don't have a country....

Country filter should (almost) always be applied @esirK ... This is how we differentiate Global, Regional and Country reports i.e. only include those countries defined in the list... If you don't do that then the report you generate will be the same regardless of the report type. `ws_104` also uses person model but we still apply country filter.

**Comment by kilemensi** [comment]
> +1 @kilemensi
> just to confirm, how will sheets 55 & 56 look like in the report? Like the current sheet 57?

Current sheet 57 has country list @esirK ... It will probably look like the updated 55/56 sheets but with extra row _or_ column showing media (Internet and Twitter).

**Comment by esirK** [comment]
> > +1 @kilemensi
> > just to confirm, how will sheets 55 & 56 look like in the report? Like the current sheet 57?
> 
> Current sheet 57 has country list @esirK ... It will probably look like the updated 55/56 sheets but with extra row _or_ column showing media (Internet and Twitter).

Yeah. I meant to ask just the form format..

**Review by kilemensi — APPROVED** [review]
🚀 @esirK 

-------

Where are my screenshots?

**Pull request merged**
