### PR TITLE
Use custom views for password reset and password reset done views.

### PR DESCRIPTION
**Pull request by esirK**
## Description

Changes the title of the password reset and password reset done forms.
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
Screenshot 2020-09-22 at 11 38 10

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
:+1: @esirK ... Any reason why it's not picking them from here: https://github.com/CodeForAfrica/gmmp/pull/88/files#diff-3256f5328cb529b3ece983deb58f06a7R12-L12?

**Comment by kilemensi** [comment]
Or if it's a Django 2 thing @esirK, may be changing https://github.com/CodeForAfrica/gmmp/pull/88/files#diff-3256f5328cb529b3ece983deb58f06a7R12-L12 to:

```python
# Admin Site Config
admin.sites.AdminSite.site_header = 'My site admin header'
admin.sites.AdminSite.site_title = 'My site admin title'
admin.sites.AdminSite.index_title = 'My site admin index'
```

may help? From: https://stackoverflow.com/a/52350466

**Comment by esirK** [comment]
> Or if it's a Django 2 thing @esirK, may be changing https://github.com/CodeForAfrica/gmmp/pull/88/files#diff-3256f5328cb529b3ece983deb58f06a7R12-L12 to:
> 
> ```python
> # Admin Site Config
> admin.sites.AdminSite.site_header = 'My site admin header'
> admin.sites.AdminSite.site_title = 'My site admin title'
> admin.sites.AdminSite.index_title = 'My site admin index'
> ```
> 
> may help? From: https://stackoverflow.com/a/52350466

@kilemensi 
I did try this but it doesn't work.
https://stackoverflow.com/a/53572673/5562041 tries to give an explanation

**Comment by kilemensi** [comment]
> > Or if it's a Django 2 thing @esirK, may be changing https://github.com/CodeForAfrica/gmmp/pull/88/files#diff-3256f5328cb529b3ece983deb58f06a7R12-L12 to:
> > ```python
> > # Admin Site Config
> > admin.sites.AdminSite.site_header = 'My site admin header'
> > admin.sites.AdminSite.site_title = 'My site admin title'
> > admin.sites.AdminSite.index_title = 'My site admin index'
> > ```
> > 
> > 
> > may help? From: https://stackoverflow.com/a/52350466
> 
> I did try this but it doesn't work.
> https://stackoverflow.com/a/53572673/5562041 tries to give an explanation

That's messed up... Did you try may be changing https://github.com/CodeForAfrica/gmmp/pull/88/files#diff-3256f5328cb529b3ece983deb58f06a7R12-L12 to:

```python
# Admin Site Config
admin.sites.AdminSite.site_header = 'My site admin header'
admin.sites.AdminSite.site_title = 'My site admin title'
admin.sites.AdminSite.index_title = 'My site admin index'
```

@esirK? From: https://stackoverflow.com/a/52350466

**Comment by kilemensi** [comment]
> @kilemensi
> I did try this but it doesn't work.
> https://stackoverflow.com/a/53572673/5562041 tries to give an explanation

Then someone should file a bug @esirK ... other views like logged_out.html seem to work fine so either this is a bug or there is a technical reason why Django is doing it this way.

**Review by kilemensi — APPROVED** [review]
:rocket:

**Comment by esirK** [comment]
> > @kilemensi
> > I did try this but it doesn't work.
> > https://stackoverflow.com/a/53572673/5562041 tries to give an explanation
> 
> Then someone should file a bug @esirK ... other views like logged_out.html seem to work fine so either this is a bug or there is a technical reason why Django is doing it this way.

Lemme dig a little bit and ask around if there is a reason why.

**Pull request merged**
