### PR TITLE
[Feature] Sheet 106, Covid stories: news subjects and sources, occupation by sex

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

Implement sheet `106`: **Covid stories: news subjects and sources, occupation by sex**

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

Screenshot from 2021-03-08 11-54-25

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by esirK** [comment]
@kilemensi  this looks good but should we also include the `N` in the results?

**Comment by kilemensi** [comment]
> @kilemensi this looks good but should we also include the `N` in the results?

Sheets `104` to `106 are` basically the same problem structure @esirK ... We either add **N** to all or we don't.

**Comment by esirK** [comment]
> > @kilemensi this looks good but should we also include the `N` in the results?
> 
> Sheets `104` to `106 are` basically the same problem structure @esirK ... We either add **N** to all or we don't.

Sure. Just thought about it after we decided to add it to the sheets we are removing the countries from but yeah we can do without it.

**Review by esirK — APPROVED** [review]
LGTM

**Pull request merged**
