### PR TITLE
Update sheet rows to reflect updated topics to ensure data is loaded

### PR DESCRIPTION
**Pull request by esirK**
## Description
Not sure when the changes happened but the current [TOPICS](https://github.com/CodeForAfrica/gmmp/blob/master/forms/modelutils.py#L15)  wording doesn't match with the current report rows wordings. This causes the historical columns not to display any data. This PR fixes that.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Damn... but alright @esirK . Is there a way of confirming which wording should be used? It's possible someone was asked to update some wording for 2020 but forgot to update TOPICS.

**Comment by esirK** [comment]
> Damn... but alright @esirK . Is there a way of confirming which wording should be used? It's possible someone was asked to update some wording for 2020 but forgot to update TOPICS.

@kilemensi
 > Is there a way of confirming which wording should be used?

Yes, we should be using the current [TOPICS](https://github.com/CodeForAfrica/gmmp/blob/master/forms/modelutils.py#L15) wording since this is what 2020 report generation uses.

Also just to rephrase what's happening.
When the report was being generated in 2015, the TOPICS were named as shown here https://github.com/CodeForAfrica/gmmp/blob/af6d31e035/forms/modelutils.py#L10
since the TOPICS have now changed, generating `historical.json` using the 2015 report that we have results to a JSON file that uses these old topics wording. The solution was to manually update the topics wordings in the 2015 report and generate a new JSON file. The reason being the 2020 report generation uses the new TOPICS.

**Comment by kilemensi** [comment]
I think I get you but I'm still lost or at least I'm still iffy @esirK :

`historical.json` gets completely replaced when someone runs `import-historical` command. Put another way, what would happen if I run `./manager.py import-historical --global --year 2010` now?

**Comment by esirK** [comment]
> `historical.json` gets completely replaced when someone runs `import-historical` command. Put another way, what would happen if I run `./manager.py import-historical --global --year 2010` now?

Yes, `historical.json` gets completely replaced but it's written according to what we have in the historical reports so for example, the **arts, entertainment, leisure, cinema, books, dance** [here](https://github.com/CodeForAfrica/gmmp/blob/fix_save_button_safari/historical.json#L3244) is being directly pulled from the row of sheet 9. Since the TOPICS that were used to write this row has changed, trying to map this data to display for 2020 won't work because of the keys(rows are used as dict keys) differences https://github.com/CodeForAfrica/gmmp/blob/677e5221c395b1d9ecf96c39ac0cf9a917fc7108/reports/report_builder.py#L4565

**Comment by kilemensi** [comment]
> Yes, `historical.json` gets com...

I totally agree with what you're saying @esirK but I'm iffy about the way you're going about: Wouldn't it be better may be to separate 2010 and 2015/2020 TOPICS values so that if importing/generating 2010 reports, 2010 values of TOPICS are used and similar for 2020?

But of course, we can do this **after** finishing the fixes and generating a full 2020 report... that is still our priority.

**Comment by kilemensi** [comment]
> > Yes, `historical.json` gets com...
> 
> I totally agree with what you're saying @esirK but I'm iffy about the way you're going about: Wouldn't it be better may be to separate 2010 and 2015/2020 TOPICS values so that if importing/generating 2010 reports, 2010 values of TOPICS are used and similar for 2020?

**Review by kilemensi — APPROVED** [review]
:rocket:

**Pull request merged**
