### PR TITLE
Ft wazimap ng integration

### PR DESCRIPTION
**Pull request by esirK**
## Description
Adds wazimap map to gmmp.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
Screenshot 2021-04-19 at 12 07 36

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
Looks alright @esirK ... Quick question though, can't we create a proper route (with view), say `/dashboard` or `/charts` or something else) that controls where charts are visualized rather than checking directly on `/static/` ?

(I know the question will still remain what if a user accesses the file in `/static/` file directly).

**Comment by esirK** [comment]
@kilemensi  
This is possible. It was actually among the first approaches I tried. 
We can have both because I'm not sure of another way of protecting the `/static` files although I'm not sure the benefit we would get from having both.

**Comment by kilemensi** [comment]
> @kilemensi
> This is possible. It was actually among the first approaches I tried.
> We can have both because I'm not sure of another way of protecting the `/static` files although I'm not sure the benefit we would get from having both.

Yes we can leave this second approach as a guard against unauthorized users for now @esirK but we should add the first approach as the default / documented route to visualisations.

**Review by kilemensi — APPROVED** [review]
🚀  @esirK 

I think lets use hurumap brand instead of wazimap.

**Pull request merged**
